Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DeepFM_test:
    model: DeepFM
    dataset_id: tiny_npz
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    hidden_units: [64, 32]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 1.e-8
    learning_rate: 1.e-3
    batch_norm: False
    net_dropout: 0
    batch_size: 128
    embedding_dim: 4
    epochs: 20
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1

DeepFM_test2:
    model: DeepFM
    dataset_id: tiny_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    hidden_units: [64, 32]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 1.e-8
    learning_rate: 1.e-3
    batch_norm: False
    net_dropout: 0
    batch_size: 128
    embedding_dim: 4
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DeepFM_default: # This is a config template
    model: DeepFM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    hidden_units: [300, 300, 300]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 0
    learning_rate: 1.e-3
    batch_norm: False
    net_dropout: 0
    batch_size: 10000
    embedding_dim: 40
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DeepFM_avazu_base: &default_avazu
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 1
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000, 2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Avazu/DeepFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false
    cov_reg: 1

DeepFM_avazu:
    <<: *default_avazu

DeepFM_avazu_cov:
    <<: *default_avazu
    cov_nondiag: 0.1
    cov_diag: 0.

DeepFM_avazu_fs: &default_avazu_fs
    <<: *default_avazu
    emb_activation: relu
    concat_emb: true
    gamma: 6

DeepFM_avazu_fs_use_low:
    <<: *default_avazu_fs
    use_low_cardinality_predict: true

DeepFM_avazu_fs_use_high_5:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 5

DeepFM_avazu_fs_use_high_4:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 4

DeepFM_avazu_fs_use_high_3:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 3

DeepFM_avazu_fs_use_high_2:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 2

DeepFM_avazu_fs_use_high_1:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 1


DeepFM_avazu_fs_random_predict:
    <<: *default_avazu_fs
    use_random_predicts: true

DeepFM_avazu_fs_masked_predict:
    <<: *default_avazu_fs
    use_masked_predict: true

DeepFM_avazu_tanh:
    <<: *default_avazu_fs
    emb_activation: tanh

DeepFM_avazu_elu:
    <<: *default_avazu_fs
    emb_activation: elu

DeepFM_avazu_sigmoid:
    <<: *default_avazu_fs
    emb_activation: sigmoid
    gamma: 1

DeepFM_avazu_silu:
    <<: *default_avazu_fs
    emb_activation: silu

DeepFM_avazu_fs_debug:
    <<: *default_avazu_fs
    gamma: 6

DeepFM_avazu_fs_exclude_self:
    <<: *default_avazu_fs
    exclude_self: true

DeepFM_avazu_fs_residual:
    <<: *default_avazu_fs
    gen_residual: true

DeepFM_avazu_group0:
    <<: *default_avazu_fs
    exp_group_idx: 0

DeepFM_avazu_group1:
    <<: *default_avazu_fs
    exp_group_idx: 1

DeepFM_avazu_group2:
    <<: *default_avazu_fs
    exp_group_idx: 2

DeepFM_avazu_symmetric:
    <<: *default_avazu
    use_fs: true

DeepFM_avazu_ab_no_sigma:
    <<: *default_avazu
    emb_activation: linear
    concat_emb: true
    gamma: 6

DeepFM_avazu_ab_no_concat:
    <<: *default_avazu
    emb_activation: relu
    concat_emb: false
    gamma: 6
    small_transformation: true

DeepFM_avazu_ab_no_concat_no_w:
    <<: *default_avazu
    emb_activation: relu
    concat_emb: false
    gamma: 6

DeepFM_avazu_ab_senet:
    <<: *default_avazu
    use_senet: true
    reduction_ratio: 5

DeepFM_avazu_ab_finalmlp:
    <<: *default_avazu
    use_finalmlp: true
    fs_hidden_units: [1000]
    fs1_context: []

DeepFM_criteo_x1_001_4b788fed: &default_criteo
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Criteo/DeepFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

DeepFM_criteo:
    <<: *default_criteo

DeepFM_criteo_fs: &default_criteo_fs
    <<: *default_criteo
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 0.1

DeepFM_criteo_symmetric:
    <<: *default_criteo_fs
    symmetric: true

DeepFM_criteo_sigmoid:
    <<: *default_criteo_fs
    emb_activation: sigmoid

DeepFM_criteo_tanh:
    <<: *default_criteo_fs
    emb_activation: tanh

DeepFM_criteo_elu:
    <<: *default_criteo_fs
    emb_activation: elu

DeepFM_criteo_silu:
    <<: *default_criteo_fs
    emb_activation: silu

DeepFM_criteo_ab_no_sigma:
    <<: *default_criteo
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 0.1

DeepFM_criteo_ab_no_concat:
    <<: *default_criteo
    emb_activation: relu
    symmetric: false
    concat_emb: false
    gamma: 0.1
    small_transformation: true

DeepFM_criteo_ab_no_concat_no_w:
    <<: *default_criteo
    emb_activation: relu
    symmetric: false
    concat_emb: false
    gamma: 0.1

DeepFM_criteo_group0:
    <<: *default_criteo_fs
    exp_group_idx: 0

DeepFM_criteo_group1:
    <<: *default_criteo_fs
    exp_group_idx: 1

DeepFM_criteo_group2:
    <<: *default_criteo_fs
    exp_group_idx: 2

DeepFM_criteo_group3:
    <<: *default_criteo_fs
    exp_group_idx: 3

DeepFM_criteo_fs_debug:
    <<: *default_criteo_fs

DeepFM_frappe_x1_001_4ae3a56e:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Frappe/DeepFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1

DeepFM_movielenslatest_x1_005_0f6d2e8e:
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 20
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    group_id: user_id
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Movielens/DeepFM_movielenslatest_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1

DeepFM_kkbox_x1_005_32cb2ca8:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [5000, 5000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3

DeepFM_amazonelectronics_x1_014_68eadb7e:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1

DeepFM_criteo_x4_024_626165ea: &default_criteo_x4
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Criteo/DeepFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

DeepFM_criteo_x4:
    <<: *default_criteo_x4

DeepFM_criteo_x4_fs:
    <<: *default_criteo_x4
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 0.1

DeepFM_criteo_x1_small: &default_criteo_small
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_small
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Criteo/DeepFM_criteo_x1_small/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1

DeepFM_criteo_small:
    <<: *default_criteo_small

DeepFM_criteo_small_fs:
    <<: *default_criteo_small
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 0.1
