Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCNv2_test:
    model: DCNv2
    dataset_id: tiny_npz
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 40
    stacked_dnn_hidden_units: [64, 32]
    parallel_dnn_hidden_units: [64, 32]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 3
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DCNv2_default: # This is a config template
    model: DCNv2
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    stacked_dnn_hidden_units: [500, 500, 500]
    parallel_dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DCNv2_criteo_x1_001_28c60688: &default_criteo
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: parallel
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [400, 400, 400]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false
    cross_drop: 0.
    use_gen_rst: false
    use_x0: false

DCNv2_criteo:
    <<: *default_criteo

DCNv2_criteo_fs: &default_criteo_fs
    <<: *default_criteo
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 0.01
    use_gen_rst: true
    gen_residual: true
    cross_drop: 0.1


CrossNet_criteo_fs:
    <<: *default_criteo_fs
    emb_activation: relu
    model_structure: crossnet_only
    use_gen_rst: true
    gen_residual: true
    gamma: 0.01
    cross_drop: 0.1




DCNv2_criteo_symmetric:
    <<: *default_criteo_fs
    symmetric: true

DCNv2_criteo_sigmoid:
    <<: *default_criteo_fs
    emb_activation: sigmoid

DCNv2_criteo_tanh:
    <<: *default_criteo_fs
    emb_activation: tanh

DCNv2_criteo_elu:
    <<: *default_criteo_fs
    emb_activation: elu

DCNv2_criteo_silu:
    <<: *default_criteo_fs
    emb_activation: silu

DCNv2_criteo_group0:
    <<: *default_criteo_fs
    exp_group_idx: 0

DCNv2_criteo_group1:
    <<: *default_criteo_fs
    exp_group_idx: 1

DCNv2_criteo_group2:
    <<: *default_criteo_fs
    exp_group_idx: 2

DCNv2_criteo_group3:
    <<: *default_criteo_fs
    exp_group_idx: 3

DCNv2_criteo_fs_ori_limited_crossnetv1:
    <<: *default_criteo
    use_fs: true

DCNv2_criteo_fs_ori_limited_crossnetv1_1layer:
    <<: *default_criteo
    use_fs: true
    num_cross_layers: 1


CrossNet_criteo:
    <<: *default_criteo
    model_structure: crossnet_only


CrossNet_criteo_symmetric:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    symmetric: true

CrossNet_criteo_sigmoid:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    emb_activation: sigmoid

CrossNet_criteo_tanh:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    emb_activation: tanh

CrossNet_criteo_elu:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    emb_activation: elu

CrossNet_criteo_silu:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    emb_activation: silu

CrossNet_criteo_group0:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    exp_group_idx: 0

CrossNet_criteo_group1:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    exp_group_idx: 1

CrossNet_criteo_group2:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    exp_group_idx: 2

CrossNet_criteo_group3:
    <<: *default_criteo_fs
    model_structure: crossnet_only
    exp_group_idx: 3

DCNv2_criteo_x4_001_005_c2376d55: &default_criteo_x4
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

DCNv2_criteo_x4:
    <<: *default_criteo_x4

DCNv2_criteo_x4_fs:
    <<: *default_criteo_x4
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 0.01

DCNv2_movielenslatest_x1_005_a53d8bd5:
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [gAUC, AUC, logloss]
    group_id: user_id
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Movielens/DCNv2_movielenslatest_x1/
    model_structure: crossnet_only
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1

DCNv2_frappe_x1_007_c207b717:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Frappe/DCN_frappe_x1/
    model_structure: parallel
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [400, 400, 400]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1

DCNv2_avazu_x4_011_19794dc6: &default_avazu
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 1
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [2000, 2000, 2000, 2000]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
    use_fs: false
    linear_fs: false
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

DCNv2_avazu:
    << : *default_avazu

DCNv2_avazu_fs: &default_avazu_fs
    << : *default_avazu
    emb_activation: relu
    concat_emb: true
    gamma: 8
    gen_residual: true
    use_gen_rst: true

DCNv2_avazu_2layer:
    << : *default_avazu
    emb_activation: relu
    concat_emb: true
    gamma: 6
    gen_residual: true
    use_gen_rst: true
    more_layers: true


DCNv2_avazu_fs_use_high:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 5

DCNv2_avazu_fs_use_high_4:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 4

DCNv2_avazu_fs_use_high_3:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 3

DCNv2_avazu_fs_use_high_2:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 2


DCNv2_avazu_fs_use_high_1:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 1

DCNv2_avazu_symmetric:
    << : *default_avazu_fs
    symmetric: true

DCNv2_avazu_cov:
    << : *default_avazu
    cov_nondiag: 0.2
    cov_diag: 0.2

DCNv2_avazu_fs_cov:
    << : *default_avazu_fs
    emb_activation: silu
    cov_nondiag: 0.
    cov_diag: 0.005

DCNv2_avazu_sigmoid:
    << : *default_avazu_fs
    emb_activation: sigmoid
    gamma: 1

DCNv2_avazu_tanh:
    << : *default_avazu_fs
    emb_activation: tanh

DCNv2_avazu_elu:
    << : *default_avazu_fs
    emb_activation: elu

DCNv2_avazu_silu:
    << : *default_avazu_fs
    emb_activation: silu

DCNv2_avazu_linear:
    << : *default_avazu_fs
    emb_activation: linear

DCNv2_avazu_group0:
    << : *default_avazu_fs
    exp_group_idx: 0

DCNv2_avazu_group1:
    << : *default_avazu_fs
    exp_group_idx: 1

DCNv2_avazu_group2:
    << : *default_avazu_fs
    exp_group_idx: 2

DCNv2_avazu_group3:
    << : *default_avazu_fs
    exp_group_idx: 3

DCNv2_avazu_test:
    << : *default_avazu_fs

DCNv2_avazu_fs_debug:
    <<: *default_avazu_fs

DCNv2_avazu_fs_exclude_self:
    <<: *default_avazu_fs
    exclude_self: true

DCNv2_avazu_debug:
    <<: *default_avazu

DCNv2_avazu_fs_residual:
    <<: *default_avazu_fs
    gen_residual: true
    use_gen_rst: true

DCNv2_avazu_fs_use_att:
    <<: *default_avazu_fs
    use_att: true
    gamma: 1
    emb_activation: linear

DCNv2_avazu_fs_use_high_cardinality_predict:
    <<: *default_avazu_fs
    use_high_cardinality_predict: true
    num_target: 5

DCNv2_avazu_fs_use_low_cardinality_predict:
    <<: *default_avazu_fs
    use_low_cardinality_predict: true
    num_target: 5

DCNv2_avazu_fs_use_random_cardinality_predict:
    <<: *default_avazu_fs
    use_random_predict: true
    num_target: 5

DCNv2_avazu_fs_use_hard_mask_predict:
    <<: *default_avazu_fs
    use_random_predict: true
    num_target: 19

DCNv2_avazu_bn:
    << : *default_avazu
    use_bn: true
    # emb_activation: tanh
    # gamma: 4

DCNv2_avazu_fs_bn:
    << : *default_avazu_fs
    use_bn: true
    emb_activation: relu
    gamma: 4

DCNv2_avazu_ab_no_sigma:
    <<: *default_avazu
    concat_emb: true
    emb_activation: linear
    gamma: 12

DCNv2_avazu_ab_no_concat:
    <<: *default_avazu
    concat_emb: false
    emb_activation: tanh
    gamma: 12
    small_transformation: true

DCNv2_avazu_ab_no_concat_no_w:
    <<: *default_avazu
    concat_emb: false
    emb_activation: tanh
    gamma: 12

CrossNet_avazu:
    << : *default_avazu
    model_structure: crossnet_only

CrossNet_avazu_fs:
    << : *default_avazu_fs
    model_structure: crossnet_only
    use_gen_rst: true
    gen_residual: true

CrossNet_avazu_fs_debug:
    <<: *default_avazu_fs
    model_structure: crossnet_only
    use_gen_rst: true
    gen_residual: true

CrossNet_avazu_debug:
    <<: *default_avazu
    model_structure: crossnet_only

CrossNet_avazu_symmetric:
    << : *default_avazu_fs
    model_structure: crossnet_only
    gamma: 24
    symmetric: true

CrossNet_avazu_sigmoid:
    <<: *default_avazu_fs
    model_structure: crossnet_only
    emb_activation: sigmoid

CrossNet_avazu_tanh:
    <<: *default_avazu_fs
    model_structure: crossnet_only
    emb_activation: tanh

CrossNet_avazu_elu:
    <<: *default_avazu_fs
    model_structure: crossnet_only
    emb_activation: elu

CrossNet_avazu_silu:
    <<: *default_avazu_fs
    model_structure: crossnet_only
    emb_activation: silu

CrossNet_avazu_group0:
    << : *default_avazu_fs
    model_structure: crossnet_only
    exp_group_idx: 0

CrossNet_avazu_group1:
    << : *default_avazu_fs
    model_structure: crossnet_only
    exp_group_idx: 1

CrossNet_avazu_group2:
    << : *default_avazu_fs
    model_structure: crossnet_only
    exp_group_idx: 2

DCNv2_avazu_fs_relu:
    << : *default_avazu
    use_fs: true
    emb_activation: relu

DCNv2_avazu_fs_silu:
    << : *default_avazu
    use_fs: true
    emb_activation: silu

DCNv2_avazu_fs_tanh:
    << : *default_avazu
    use_fs: true
    emb_activation: tanh

DCNv2_avazu_fs_elu:
    << : *default_avazu
    use_fs: true
    emb_activation: elu


DCNv2_avazu_stack:
    << : *default_avazu
    model_structure: stacked

DCNv2_avazu_tanh_stack:
    << : *default_avazu
    model_structure: stacked

DCNv2_avazu_elu_stack:
    << : *default_avazu
    model_structure: stacked

DCNv2_avazu_dnn_classifier:
    << : *default_avazu

DCNv2_avazu_dnn_classifier_elu:
    << : *default_avazu

DCNv2_avazu_dnn_classifier_tanh:
    << : *default_avazu
